### ISSUE TITLE
The example app crashing after clicking on chat. 

### ISSUE THREAD

**Issue by abhishekove** [Piasy/FlutterWebRTCDataChannel#5]
The example app crashing after clicking on chat. 
url used is https://appr.tc/ .

**Comment by abhishekove** [comment]
D/RoomRTCClient(26407): WSS POST url: https://apprtc-ws.webrtc.org:443
D/RoomRTCClient(26407): Request TURN from: https://appr.tc/v1alpha/iceconfig?key=
E/WSRTCClient(26407): Room IO error: java.io.IOException: Non-200 response when requesting TURN server from https://appr.tc/v1alpha/iceconfig?key= : HTTP/1.1 405 Method Not Allowed
E/AndroidRuntime(26407): FATAL EXCEPTION: WSRTCClient
E/AndroidRuntime(26407): Process: com.dev.gravi, PID: 26407
E/AndroidRuntime(26407): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: WSRTCClient
E/AndroidRuntime(26407): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1230)
E/AndroidRuntime(26407): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:862)
E/AndroidRuntime(26407): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime(26407): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:384)
E/AndroidRuntime(26407): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:176)
E/AndroidRuntime(26407): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.error(EventChannel.java:230)
E/AndroidRuntime(26407): 	at com.github.piasy.webrtcdatachannel.WebRTCDataChannelPlugin.notifyError(WebRTCDataChannelPlugin.java:257)
E/AndroidRuntime(26407): 	at com.github.piasy.webrtcdatachannel.WebRTCDataChannelPlugin.onChannelError(WebRTCDataChannelPlugin.java:186)
E/AndroidRuntime(26407): 	at org.appspot.apprtc.WebSocketRTCClient$8.run(WebSocketRTCClient.java:364)
E/AndroidRuntime(26407): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(26407): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26407): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(26407): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/TransportRuntime.SQLiteEventStore(26407): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(26407): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1576611581 in 1000ms(Backend next call timestamp 1630240478254). Attempt 1
I/Process (26407): Sending signal. PID: 26407 SIG: 9
Lost connection to device
